# Descriptors
- Lipinski
- Mol Weight done
- H donors done
- H acceptors done
- aromatic rings
- rotatable bonds done
- Lipophilicity/Hydrophilicity (LogP / LogD) done
- Topological Polar Surface Area (TPSA) done
- Absorption
- Distribution
- Metabolism
- Clearance

In [20]:
%pip install admet-ai

Requirement already satisfied: admet-ai in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (2.0.1)
Requirement already satisfied: chemprop>=2.2.2 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (2.3.0)
Requirement already satisfied: lightning in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (2.6.5)
Requirement already satisfied: numpy in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (2.1.3)
Requirement already satisfied: pandas in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (2.2.3)
Requirement already satisfied: rdkit>=2025.9.5 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (2026.3.4)
Requirement already satisfied: seaborn in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (0.13.2)
Requirement already satisfied: torch>=2.8.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (2.13.0)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (4.67.1)
Requirement already satisfied: typed-argument-parser>=1.11.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from admet-ai) (1.12.0)
Requirement already satisfied: scikit-learn in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (1.6.1)
Requirement already satisfied: scipy in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (1.15.3)
Requirement already satisfied: astartes[molecules] in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (1.3.3)
Requirement already satisfied: ConfigArgParse in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (1.7.5)
Requirement already satisfied: rich in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (13.9.4)
Requirement already satisfied: descriptastorus in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (2.8.0)
Requirement already satisfied: cuik_molmaker_pin in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (2026.3.4)
Requirement already satisfied: myerson>=1.0.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from chemprop>=2.2.2->admet-ai) (1.0.1)
Requirement already satisfied: PyYAML<8.0,>5.4 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from lightning->admet-ai) (6.0.2)
Requirement already satisfied: fsspec<2028.0,>=2022.5.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (2025.3.2)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from lightning->admet-ai) (0.15.3)
Requirement already satisfied: packaging<27.0,>=23.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from lightning->admet-ai) (24.2)
Requirement already satisfied: torchmetrics<3.0,>0.7.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from lightning->admet-ai) (1.9.0)
Requirement already satisfied: typing-extensions<6.0,>4.5.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from lightning->admet-ai) (4.12.2)
Requirement already satisfied: pytorch-lightning in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from lightning->admet-ai) (2.6.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (3.11.10)
Requirement already satisfied: filelock in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from torch>=2.8.0->admet-ai) (3.17.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from torch>=2.8.0->admet-ai) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from torch>=2.8.0->admet-ai) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from torch>=2.8.0->admet-ai) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from torch>=2.8.0->admet-ai) (3.1.6)
Requirement already satisfied: colorama in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from tqdm>=4.66.3->admet-ai) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (1.18.0)
Requirement already satisfied: idna>=2.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->admet-ai) (3.7)
Requirement already satisfied: Pillow in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from rdkit>=2025.9.5->admet-ai) (11.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.8.0->admet-ai) (1.3.0)
Requirement already satisfied: docstring-parser>=0.15 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from typed-argument-parser>=1.11.0->admet-ai) (0.18.0)
Requirement already satisfied: tabulate in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from astartes[molecules]->chemprop>=2.2.2->admet-ai) (0.9.0)
Requirement already satisfied: aimsim_core in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from astartes[molecules]->chemprop>=2.2.2->admet-ai) (2.2.3)
Requirement already satisfied: psutil in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (5.9.0)
Requirement already satisfied: padelpy in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (0.1.17)
Requirement already satisfied: mhfp in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (1.9.6)
Requirement already satisfied: mordredcommunity in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (2.0.7)
Requirement already satisfied: multiprocess>=0.70 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (0.70.19)
Requirement already satisfied: dill>=0.4.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from multiprocess>=0.70->aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (0.4.1)
Requirement already satisfied: pandas-flavor in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from descriptastorus->chemprop>=2.2.2->admet-ai) (0.8.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from jinja2->torch>=2.8.0->admet-ai) (3.0.2)
Requirement already satisfied: six in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from mordredcommunity->aimsim_core->astartes[molecules]->chemprop>=2.2.2->admet-ai) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from pandas->admet-ai) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from pandas->admet-ai) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from pandas->admet-ai) (2025.2)
Requirement already satisfied: xarray in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from pandas-flavor->descriptastorus->chemprop>=2.2.2->admet-ai) (2025.4.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from rich->chemprop>=2.2.2->admet-ai) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from rich->chemprop>=2.2.2->admet-ai) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->chemprop>=2.2.2->admet-ai) (0.1.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from scikit-learn->chemprop>=2.2.2->admet-ai) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from scikit-learn->chemprop>=2.2.2->admet-ai) (3.5.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from seaborn->admet-ai) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->admet-ai) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->admet-ai) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->admet-ai) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->admet-ai) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\pham.congdat\appdata\local\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->admet-ai) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit import RDLogger
from rdkit.Chem import Descriptors, Crippen, rdMolDescriptors, QED
from rdkit.Chem import Lipinski
from rdkit.Chem.Descriptors import MolWt
from rdkit.Chem.Crippen import MolLogP
from admet_ai import ADMETModel

### Disable RDKit informational messages ###
RDLogger.DisableLog('rdApp.*')

#############
### Setup ###
#############

supply = Chem.SmilesMolSupplier(
    'standardized_smiles.smi',
    delimiter='\t',
    titleLine=False
    )

model = ADMETModel()

#######################
### Get Descriptors ###
#######################

def calculate_descriptors(mol, admet_model=None):

    smiles = Chem.MolToSmiles(mol)
    
    descriptors = {
        "Compound": Chem.MolToSmiles(mol),
        "MW": round(Descriptors.MolWt(mol),2),
        "LogP": round(Crippen.MolLogP(mol),2),
        "HBD": Lipinski.NumHDonors(mol),
        "HBA": Lipinski.NumHAcceptors(mol),
        "Aromatic ring number": rdMolDescriptors.CalcNumAromaticRings(mol),
        "TPSA": round(Descriptors.TPSA(mol),2),
        "RotB": Descriptors.NumRotatableBonds(mol),
        "QED": round(QED.qed(mol),2),
        "Formal_Charge": Chem.GetFormalCharge(mol), 
    }

    # Add hERG prediction
    if admet_model is not None:
        preds = admet_model.predict(smiles=smiles)
        descriptors["hERG"] = preds.get("hERG", None)
        descriptors["Caco2_Wang"] = preds.get("Caco2_Wang", None)
        descriptors["BBB_Martins"] = preds.get("BBB_Martins", None)

    else:
        descriptors["hERG"] = None
        descriptors["Caco2_Wang"] = None
        descriptors["BBB_Martins"] = None
    
    return descriptors

descriptor_table = []

for i, mol in enumerate(supply, start=0):
    if supply is not None:
        descriptor_table.append(calculate_descriptors(mol, admet_model=model))
        
##############
### Output ###
##############

df = pd.DataFrame(descriptor_table)
df

SMILES to Mol: 100%|██████████| 1/1 [00:00<00:00, 1232.17it/s]
Computing physchem properties: 100%|██████████| 1/1 [00:00<00:00, 59.51it/s]
Dropping last batch of size 1 to avoid issues with batch normalization     (dataset size = 1, batch_size = 64)
GPU available: False, used: False 0/2 [00:00<?, ?it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\utilities\_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Output()

Output()

Output()

Output()

GPU available: False, used: False 1/2 [00:00<00:00,  2.86it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

Output()

Output()

Output()

Output()

model ensembles: 100%|██████████| 2/2 [00:00<00:00,  2.79it/s]
SMILES to Mol: 100%|██████████| 1/1 [00:00<00:00, 2483.31it/s]
Computing physchem properties: 100%|██████████| 1/1 [00:00<00:00, 49.48it/s]
Dropping last batch of size 1 to avoid issues with batch normalization     (dataset size = 1, batch_size = 64)
GPU available: False, used: False 0/2 [00:00<?, ?it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\utilities\_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Output()

Output()

Output()

Output()

GPU available: False, used: False 1/2 [00:00<00:00,  2.80it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

Output()

Output()

Output()

Output()

model ensembles: 100%|██████████| 2/2 [00:00<00:00,  2.86it/s]
SMILES to Mol: 100%|██████████| 1/1 [00:00<00:00, 1323.12it/s]
Computing physchem properties: 100%|██████████| 1/1 [00:00<00:00, 59.86it/s]
Dropping last batch of size 1 to avoid issues with batch normalization     (dataset size = 1, batch_size = 64)
GPU available: False, used: False 0/2 [00:00<?, ?it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\utilities\_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Output()

Output()

Output()

Output()

GPU available: False, used: False 1/2 [00:00<00:00,  2.68it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

Output()

Output()

Output()

Output()

model ensembles: 100%|██████████| 2/2 [00:00<00:00,  2.85it/s]
SMILES to Mol: 100%|██████████| 1/1 [00:00<00:00, 1317.72it/s]
Computing physchem properties: 100%|██████████| 1/1 [00:00<00:00, 62.25it/s]
Dropping last batch of size 1 to avoid issues with batch normalization     (dataset size = 1, batch_size = 64)
GPU available: False, used: False 0/2 [00:00<?, ?it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\utilities\_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Output()

Output()

Output()

Output()

GPU available: False, used: False 1/2 [00:00<00:00,  3.01it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

Output()

Output()

Output()

Output()

model ensembles: 100%|██████████| 2/2 [00:00<00:00,  3.00it/s]
SMILES to Mol: 100%|██████████| 1/1 [00:00<00:00, 1105.80it/s]
Computing physchem properties: 100%|██████████| 1/1 [00:00<00:00, 60.92it/s]
Dropping last batch of size 1 to avoid issues with batch normalization     (dataset size = 1, batch_size = 64)
GPU available: False, used: False 0/2 [00:00<?, ?it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\utilities\_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Output()

Output()

Output()

Output()

Output()

GPU available: False, used: False 1/2 [00:00<00:00,  2.75it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

Output()

Output()

Output()

Output()

model ensembles: 100%|██████████| 2/2 [00:00<00:00,  2.88it/s]

,Compound,MW,LogP,HBD,HBA,Aromatic ring number,TPSA,RotB,QED,Formal_Charge,hERG,Caco2_Wang,BBB_Martins
0,[NH-]S(=O)(=O)C[C@@H]1CCN1C(=O)COc1cccc(O)c1,299.33,0.75,1,5,1,107.71,5,0.86,-1,0.070363,-5.739512,0.541252
1,CS(=O)(=O)N1CC(CNC(=O)c2cc[nH]c2C(=O)[O-])C1,300.32,-2.00,2,5,1,122.40,5,0.65,-1,0.020325,-5.195439,0.824922
2,NS(=O)(=O)C[C@@H]1CCN1C(=O)COc1cccc(O)c1,300.34,-0.34,2,5,1,109.93,5,0.77,0,0.135447,-5.313101,0.669595
3,O=C(CN1CC=CS1(=O)=O)NCc1nccnc1Cl,302.74,-0.09,1,5,1,92.26,4,0.84,0,0.021078,-4.835744,0.937525
4,O=C(CNC(=O)[C@H](O)Cc1ccccc1)NCc1nnn[n-]1,303.30,-1.84,3,6,2,131.20,7,0.55,-1,0.053596,-5.958936,0.895227

In [25]:
model = ADMETModel()
#preds = model.predict(smiles="O(c1ccc(cc1)CCOC)CC(O)CNC(C)C")
preds = model.predict(smiles="[NH-]S(=O)(=O)C[C@@H]1CCN1C(=O)COc1cccc(O)c1")
print(preds)

SMILES to Mol: 100%|██████████| 1/1 [00:00<00:00, 1073.81it/s]
Computing physchem properties: 100%|██████████| 1/1 [00:00<00:00, 70.67it/s]
Dropping last batch of size 1 to avoid issues with batch normalization     (dataset size = 1, batch_size = 64)
GPU available: False, used: False 0/2 [00:00<?, ?it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\utilities\_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
C:\Users\pham.congdat\AppData\Local\anaconda3\Lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:434: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Output()

Output()

Output()

Output()

GPU available: False, used: False 1/2 [00:00<00:00,  2.86it/s]
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

Output()

Output()

Output()

Output()

model ensembles: 100%|██████████| 2/2 [00:00<00:00,  2.99it/s]

{'molecular_weight': 299.328, 'logP': 0.7538999999999993, 'hydrogen_bond_acceptors': 5.0, 'hydrogen_bond_donors': 1.0, 'Lipinski': 4.0, 'QED': 0.8629279329939437, 'stereo_centers': 1.0, 'tpsa': 107.71000000000001, 'PAINS_alert': 0.0, 'BRENK_alert': 0.0, 'NIH_alert': 0.0, 'AMES': 0.42142972350120544, 'BBB_Martins': 0.5412521362304688, 'Bioavailability_Ma': 0.7395628690719604, 'CYP1A2_Veith': 0.005407499615103006, 'CYP2C19_Veith': 0.02123120054602623, 'CYP2C9_Substrate_CarbonMangels': 0.17698228359222412, 'CYP2C9_Veith': 0.009541028179228306, 'CYP2D6_Substrate_CarbonMangels': 0.038848407566547394, 'CYP2D6_Veith': 0.019444521516561508, 'CYP3A4_Substrate_CarbonMangels': 0.21521799266338348, 'CYP3A4_Veith': 0.010122527368366718, 'Carcinogens_Lagunin': 0.2892874777317047, 'ClinTox': 0.18978209793567657, 'DILI': 0.5055758357048035, 'HIA_Hou': 0.7690678834915161, 'NR-AR-LBD': 0.03467001020908356, 'NR-AR': 0.04551877826452255, 'NR-AhR': 0.01407268363982439, 'NR-Aromatase': 0.009266768582165241, 'NR-ER-LBD': 0.02592194452881813, 'NR-ER': 0.14199648797512054, 'NR-PPAR-gamma': 0.010167917236685753, 'PAMPA_NCATS': 0.10006488859653473, 'Pgp_Broccatelli': 0.010253578424453735, 'SR-ARE': 0.0814882218837738, 'SR-ATAD5': 0.015069926157593727, 'SR-HSE': 0.01828910782933235, 'SR-MMP': 0.005843468941748142, 'SR-p53': 0.04346960037946701, 'Skin_Reaction': 0.5673311948776245, 'hERG': 0.07036285847425461, 'Caco2_Wang': -5.7395124435424805, 'Clearance_Hepatocyte_AZ': 29.520259857177734, 'Clearance_Microsome_AZ': 5.519238471984863, 'Half_Life_Obach': -3.0248544216156006, 'HydrationFreeEnergy_FreeSolv': -17.162296295166016, 'LD50_Zhu': 1.5810821056365967, 'Lipophilicity_AstraZeneca': -0.43606990575790405, 'PPBR_AZ': 47.315792083740234, 'Solubility_AqSolDB': -0.5123113393783569, 'VDss_Lombardo': 1.592455267906189, 'molecular_weight_drugbank_approved_percentile': 40.14059753954306, 'logP_drugbank_approved_percentile': 29.560632688927946, 'hydrogen_bond_acceptors_drugbank_approved_percentile': 61.880492091388405, 'hydrogen_bond_donors_drugbank_approved_percentile': 36.59050966608085, 'Lipinski_drugbank_approved_percentile': 63.44463971880493, 'QED_drugbank_approved_percentile': 96.69595782073814, 'stereo_centers_drugbank_approved_percentile': 55.32513181019333, 'tpsa_drugbank_approved_percentile': 72.44288224956064, 'PAINS_alert_drugbank_approved_percentile': 47.59226713532514, 'BRENK_alert_drugbank_approved_percentile': 25.869947275922673, 'NIH_alert_drugbank_approved_percentile': 37.188049209138846, 'AMES_drugbank_approved_percentile': 71.9859402460457, 'BBB_Martins_drugbank_approved_percentile': 35.887521968365554, 'Bioavailability_Ma_drugbank_approved_percentile': 39.19156414762742, 'CYP1A2_Veith_drugbank_approved_percentile': 25.13181019332162, 'CYP2C19_Veith_drugbank_approved_percentile': 26.22144112478032, 'CYP2C9_Substrate_CarbonMangels_drugbank_approved_percentile': 64.3585237258348, 'CYP2C9_Veith_drugbank_approved_percentile': 30.931458699472763, 'CYP2D6_Substrate_CarbonMangels_drugbank_approved_percentile': 26.045694200351495, 'CYP2D6_Veith_drugbank_approved_percentile': 34.481546572934974, 'CYP3A4_Substrate_CarbonMangels_drugbank_approved_percentile': 28.26010544815466, 'CYP3A4_Veith_drugbank_approved_percentile': 34.55184534270651, 'Carcinogens_Lagunin_drugbank_approved_percentile': 75.39543057996485, 'ClinTox_drugbank_approved_percentile': 68.64674868189807, 'DILI_drugbank_approved_percentile': 55.922671353251324, 'HIA_Hou_drugbank_approved_percentile': 21.72231985940246, 'NR-AR-LBD_drugbank_approved_percentile': 77.57469244288225, 'NR-AR_drugbank_approved_percentile': 73.84885764499121, 'NR-AhR_drugbank_approved_percentile': 44.88576449912127, 'NR-Aromatase_drugbank_approved_percentile': 38.840070298769774, 'NR-ER-LBD_drugbank_approved_percentile': 60.140597539543066, 'NR-ER_drugbank_approved_percentile': 72.54833040421794, 'NR-PPAR-gamma_drugbank_approved_percentile': 58.31282952548331, 'PAMPA_NCATS_drugbank_approved_percentile': 17.363796133567664, 'Pgp_Broccatelli_drugbank_approved_percentile': 33.286467486818985, 'SR-ARE_drugbank_approved_percentile': 38.94551845342707, 'SR-ATAD5_drugbank_approved_percentile': 59.40246045694201, 'SR-HSE_drugbank_approved_percentile': 52.970123022847105, 'SR-MMP_drugbank_approved_percentile': 30.228471001757473, 'SR-p53_drugbank_approved_percentile': 57.71528998242531, 'Skin_Reaction_drugbank_approved_percentile': 55.922671353251324, 'hERG_drugbank_approved_percentile': 27.768014059753956, 'Caco2_Wang_drugbank_approved_percentile': 18.558875219683657, 'Clearance_Hepatocyte_AZ_drugbank_approved_percentile': 47.94376098418278, 'Clearance_Microsome_AZ_drugbank_approved_percentile': 29.455184534270654, 'Half_Life_Obach_drugbank_approved_percentile': 17.152899824253076, 'HydrationFreeEnergy_FreeSolv_drugbank_approved_percentile': 24.780316344463973, 'LD50_Zhu_drugbank_approved_percentile': 6.994727592267136, 'Lipophilicity_AstraZeneca_drugbank_approved_percentile': 24.42882249560633, 'PPBR_AZ_drugbank_approved_percentile': 25.940246045694202, 'Solubility_AqSolDB_drugbank_approved_percentile': 89.52548330404218, 'VDss_Lombardo_drugbank_approved_percentile': 52.196836555360285}

In [29]:
preds.get("hERG")

0.07036285847425461

In [6]:
df2 = pd.DataFrame([preds])
df2

,molecular_weight,logP,hydrogen_bond_acceptors,hydrogen_bond_donors,Lipinski,QED,stereo_centers,tpsa,PAINS_alert,BRENK_alert,...,Caco2_Wang_drugbank_approved_percentile,Clearance_Hepatocyte_AZ_drugbank_approved_percentile,Clearance_Microsome_AZ_drugbank_approved_percentile,Half_Life_Obach_drugbank_approved_percentile,HydrationFreeEnergy_FreeSolv_drugbank_approved_percentile,LD50_Zhu_drugbank_approved_percentile,Lipophilicity_AstraZeneca_drugbank_approved_percentile,PPBR_AZ_drugbank_approved_percentile,Solubility_AqSolDB_drugbank_approved_percentile,VDss_Lombardo_drugbank_approved_percentile
0,267.369,1.6132,4.0,2.0,4.0,0.71357,1.0,50.72,0.0,0.0,...,64.393673,52.126538,12.302285,40.913884,63.866432,24.182777,24.323374,14.446397,83.022847,57.820738